# Модель предсказания инсульта


```
Описание Датасета.

1) gender: 0, 1

"Male", "Female"


2) age: возраст пациента


3) hypertension: 0, если у пациента нет гипертонии, 1, если у пациента гипертония


4) heart_disease: 0, если у пациента нет заболеваний сердца, 1, если у пациента есть заболевание сердца


5) ever_married: 0 или 1

"No" или "Yes"


6) work_type: 0, 1, 2, 3, 4

"никогда не работавший", "частный", "самозанятый", "государственный", "детский" 


7) Residence_type: 0 или 1

"Сельская" или "Городская"


8) avg_glucose_level: средний уровень глюкозы в крови


9) bmi: индекс массы тела


11) smoking_status: 0, 1, 2, 3

«Никогда не курил», «Раньше курил», «Курит» или «Неизвестно»


12) stroke: 1, если у пациента был инсульт или 0, если не инсульт
```

## Пример 1

In [1]:
import pandas as pd
from joblib import load

data = pd.read_csv('all_data.csv').drop(['Unnamed: 0'], axis=1)

# сократим всю таблицу до 2 примеров от каждого класса для удобства
data = pd.concat([data.query('stroke == 0').sample(2), data.query('stroke == 1').sample(2)])

display(data)

# Загрузка модели из файла с помощью функции load
model = load('model.joblib')

predict = [x[1] for x in model.predict_proba(data.drop('stroke', axis=1))]
predict =  [round(x, 2) for x in predict]

print('Вероятность от 0 до 1:', predict)
print('Реальные значения:', data['stroke'].to_list())

,gender,age,hypertension,heart_disease,ever_married,work_type,residence_type,avg_glucose_level,bmi,smoking_status,stroke
1902,0,61.0,0,0,1,1,0,99.35,26.1,2,0
1730,0,36.0,0,0,1,1,0,90.22,28.7,1,0
83,0,79.0,1,0,0,3,1,98.02,22.3,1,1
44,1,81.0,0,0,1,1,1,72.81,26.3,0,1

Вероятность от 0 до 1: [0.1, 0.0, 0.97, 0.97]
Реальные значения: [0, 0, 1, 1]

## Пример 2

In [2]:
import pandas as pd
from joblib import load

example =  {'gender': 1,
            'age': 80,
            'hypertension': 0,
            'heart_disease': 1,
            'ever_married': 1,
            'work_type': 1,
            'residence_type': 0,
            'avg_glucose_level': 105.92,
            'bmi': 32.5,
            'smoking_status': 0}

example.keys()
example.values()
example = pd.DataFrame(data=[example.values()], columns=example.keys())

display(example)

# Загрузка модели из файла с помощью функции load
model = load('model.joblib')

predict = round(model.predict_proba(example).reshape(-1)[1], 2)

# Прогноз
print('Вероятность от 0 до 1:', predict)
print('Реальное значение: 1')

,gender,age,hypertension,heart_disease,ever_married,work_type,residence_type,avg_glucose_level,bmi,smoking_status
0,1,80,0,1,1,1,0,105.92,32.5,0

Вероятность от 0 до 1: 0.98
Реальное значение: 1