### Первый пример

In [8]:
import json

with open('json_df.json', 'r') as f:
    data = json.load(f)
    
data = pd.DataFrame(data)
print('Пример')
display(data)

Пример

,sex,height,weight,bmi,bsa,age,diagnosis,medication_main,medications_taken,days_in_hospital,...,lg_hipoplaz,pg_big,pg_hypertrop,dmgp,ekg_sinus,ekg_eos,ekg_qrs,ekg_qrst,ekg_pq,total
0,1,70.0,6.75,78.0,10.5,10.0,тетрада фалло,аспирин,13,70,...,0,-1,0,0,1,4,0.06,0.0,0.1,6

### Второй пример. Ручной ввод

In [ ]:
# Пример 38 из тестового набора. Заполнять нужно как в примере. Т.е sex это 1, не 1.0. Это важно.

sex                                                                  1
height                                                            70.0
weight                                                            6.75
bmi                                                              80.68
bsa                                                               0.37
age                                                               10.5

diagnosis                         'тетрада фалло  гипоплазия клапан легочный артерия  функционировать системно  легочный анастомоз по блелок  слева от 26 09 2016г  нк 0 ст  артериальный гипоксемия  последствие перинатальный поражение цнс  синдром тонусный   двигательный расстройство  мышечный дистония  гипертензионный  синдром  гипотрофия 2 степень  13 03 2017   операция  перевязка ранее налагать анастомоз по           синтетический протез слева  радикальный коррекция тетрада фалло с пластика выводной отдел правый желудочек и ствол легочный артерия ксеноперикардиальный заплата  ушивание овальный окно  в условие ик  гипотермия и фхкп   нк 2а ст\n'            
        
medication_main                   'аспирин в послеопрационном  периоде'
medications_taken                 ' '
days_in_hospital                                                    13
fv                                                                70.0
lg_kdr_size                                                       -1.0
lg_hipoplaz                                                          0
pg_big                                                              -1
pg_hypertrop                                                         0
dmgp                                                                 0
ekg_sinus                                                            1
ekg_eos                                                              4
ekg_qrs                                                           0.06
ekg_qrst                                                           0.0
ekg_pq                                                             0.1
total                                                                3

In [2]:
import pandas as pd

labels = ['sex','height','weight','bmi',
          'bsa','age','diagnosis',
          'medication_main','medications_taken',
          'days_in_hospital','fv','lg_kdr_size',
          'lg_hipoplaz','pg_big','pg_hypertrop',
          'dmgp','ekg_sinus','ekg_eos','ekg_qrs',
          'ekg_qrst','ekg_pq','total']
types = ['int64','float64','float64','float64','float64',
         'float64','object','object','object','int64',
         'float64','float64','int64','int64','int64',
         'int64','int64','int64','float64','float64',
         'float64','int64']

data = pd.DataFrame()
i = 0
while i<len(labels):
    value = input(f'{labels[i]}: ')
    try:
        data[labels[i]] = pd.Series([value]).astype(types[i])
        i += 1
    except:
        print(f'Неверный формат для {labels[i]}! Важны детали. Введите в стиле float, int или str. Пример в ячейке выше!')
        
display(data)

sex: 1
height: 70.0
weight: 6.75
bmi: 80.68
bsa: 0.37
age: 10.5
diagnosis: 'тетрада фалло  гипоплазия клапан легочный артерия  функционировать системно  легочный анастомоз по блелок  слева от 26 09 2016г  нк 0 ст  артериальный гипоксемия  последствие перинатальный поражение цнс  синдром тонусный   двигательный расстройство  мышечный дистония  гипертензионный  синдром  гипотрофия 2 степень  13 03 2017   операция  перевязка ранее налагать анастомоз по           синтетический протез слева  радикальный коррекция тетрада фалло с пластика выводной отдел правый желудочек и ствол легочный артерия ксеноперикардиальный заплата  ушивание овальный окно  в условие ик  гипотермия и фхкп   нк 2а ст\n'
medication_main: 'аспирин в послеопрационном  периоде'
medications_taken: ' '
days_in_hospital: 13
fv: 70.0
lg_kdr_size: -1.0
lg_hipoplaz: 0
pg_big: -1
pg_hypertrop: 0
dmgp: 0
ekg_sinus: 1
ekg_eos: 4
ekg_qrs: 0.06
ekg_qrst: 0.0
ekg_pq: 0.1
total: 3

,sex,height,weight,bmi,bsa,age,diagnosis,medication_main,medications_taken,days_in_hospital,...,lg_hipoplaz,pg_big,pg_hypertrop,dmgp,ekg_sinus,ekg_eos,ekg_qrs,ekg_qrst,ekg_pq,total
0,1,70.0,6.75,80.68,0.37,10.5,'тетрада фалло гипоплазия клапан легочный арт...,'аспирин в послеопрационном периоде',' ',13,...,0,-1,0,0,1,4,0.06,0.0,0.1,3

## Модель

In [7]:
import pandas as pd
from joblib import dump, load
model = load('model.joblib')

answer = round(model.predict_proba(data)[0][1]*100)
print('Вероятность врожденного порога сердца у ребенка: {}%'.format(answer))

Вероятность врожденного порога сердца у ребенка: 16%